name: Auto Tagging on Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: List commits
        run: |
          git log --oneline
          echo "Hello World"   

      - name: Check Commit Messages
        id: check_commit_messages
        run: |
          # Retrieve the list of commits in the PR
          PR_COMMITS=$(git log --format=%s ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

          echo "Commit messages read $PR_COMMITS"   
          echo "Found commit messages containing 'feat' or 'fix'."
          echo "Incrementing major version."
          echo "::set-output name=version::major"

      - name: Create Tag
        run: |
          git tag -a v${{ github.run_number }} -m "Automatically created tag"
          git push origin v${{ github.run_number }}
